version: '3'
services:
  spawner:
    build:
      context: .
      dockerfile: Dockerfile.spawner
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./dockerfiles:/dockerfiles  # Mounts the folder containing Dockerfiles
    networks:
      - my_network
    ports:
      - "8081:8080"  # Expose port for spawner API

networks:
  my_network:
